### ISSUE TITLE
Animated sorting changes do not appear

### ISSUE THREAD

**Issue by ened** [gildaswise/firestore_ui#4]
It seems like resorting / moving items around is not supported yet.
The use case can happen quite often, when a list is updated & items change positions.

The values themselves are updated correctly.

It works OK when using the example outlined in https://pub.dartlang.org/packages/cloud_firestore, just not nicely animated. I would prefer for the items to slide into their correct positions.

**Comment by gildaswise** [comment]
Hey, thanks for submitting this issue! As this is a port from firebase_database's [UI part](https://github.com/flutter/plugins/tree/master/packages/firebase_database/lib/ui), I removed `onChildMoved` because the animation wasn't noticeable enough; I can try porting it but it'll still depend on the animation you pass to the builder so making them slide might not be possible. I appreciate if you submit a PR that tries to do this!

**Comment by gildaswise** [comment]
It's been a while since I reviewed this issue, the problem lies on a very simple problem: Firestore doesn't have something as `onChildMoved`, and the reason for removing it was that. For that to work, FirestoreList would have to check locally whether there was a move action or not, and that's probably not ideal to do on a streamable list every time something changes. 

I'll close this issue but if someone wants to tackle this problem, feel free.
