### ISSUE TITLE
Example with pagination

### ISSUE THREAD

**Issue by dvird** [gildaswise/firestore_ui#7]
Can you give us an example of how is it combined with pagination?

**Comment by gildaswise** [comment]
Hey, dvird! Sorry about the delay! On my apps, until now, I never needed proper pagination because it's just cheaper to have the streamable list work like it does now, and Flutter only renders the items that are on the screen so you don't have to worry about performance when loading a very big list; it's doable by using `startAt`, `startAfter` and `endAt`, `endAfter` and maintaining the last loaded index. 

There's a [whole video](https://www.youtube.com/watch?v=poqTHxtDXwU) about it and you can extract your solution from there! It's basically storing the last loaded index, then if that's available you just have to add `startAfter` to your query.

**Comment by dvird** [comment]
I know how to make pagination with firestore, but whats im looking for is an example how can we make with your library. I replaced to stream builder because I didnt succeed to make it happen when using your library

**Comment by gildaswise** [comment]
It's basically impossible since this library is meant to be a streamable list, and its code reflects that and wouldn't work with pagination that well, if at all; to use pagination it's just easier to build your own implementation over a ListView Widget.
